### PR TITLE
Remove Blaze dependency

### PR DESCRIPTION
**Pull request by gabrielhpugliese**
This removes Blaze completely. This PR is patched with https://github.com/jedwards1211/meteor-webpack-react/pull/91 so accept it before accepting this one or just accept this and close the #91 
Feel free to close this if you think it's a bad idea (I don't think it is :)

### CODE REVIEW

**Comment by haydnhkim** [comment]
+1

**Comment by jbbr** [comment]
I think it's a good idea. I prefer using static-html also.

But: This is a skeleton/ starting point and when starting to write an application with this skeleton many will use accounts-ui to get authentication working quick and easy - So until there is no React alternative to accounts-ui I would keep blaze enabled by default.

Maybe writing a full SSR example in a separate branch with disabled blaze and routing e.g with react-router would be a good addition?

As jedwards1211 is bundling the build scripts into a webpack plugin (branch https://github.com/jedwards1211/meteor-webpack-react/commits/webpack-meteor-tools), in the future it will be easier to add multiple examples for different configurations

**Comment by gabrielhpugliese** [comment]
I'm building the LoginButtons for React on my fork (gonna create a package or something later): https://github.com/gabrielhpugliese/meteor-webpack-react/commit/ecddbc70cf773bddbc4173c953129c213c257692
Noticed that it's a huge work!

Yeah, I think it would be better to have an example somewhere without Blaze that we can clone and start right on that point.

**Comment by jedwards1211** [comment]
I agree with @jbbr, and yeah it becomes a burden trying to please everyone with a skeleton project.  But I appreciate your interest and efforts to contribute improvements, and I'll probably use this in my own projects, so thanks! :)  I'd be happy to see multiple skeleton projects with different styles hosted by different people in the future, it would definitely help for people to be able to pick and choose a configuration tailored to their needs.  I can try to put this in a branch though.  I'll leave this open until I get around to it

**Comment by jedwards1211** [comment]
I'm going to close this since I decided not to remove Blaze in the main skeleton project

**Comment by gabrielhpugliese** [comment]
:+1:

**Pull request closed without merging**
