### PR TITLE
Emit sourcemaps on client

### PR DESCRIPTION
**Pull request by gabrielhpugliese**
This is needed to debug :+1: This is how it looks like now:
image

### CODE REVIEW

**Comment by jbbr** [comment]
devTool 'source-map' does not have any cache. So it's very slow. Better use `cheap-module-source-map` or `eval-source-map`.

I think the reason why they use currently only simple `eval` source maps in this skeleton is that the huge redbox-react error plugin does not show correct line numbers and filenames when not using `eval`.
And `eval` is the fastes of course and source maps are readable (but line numbers are wrong because caused by babel transpiling).

**Comment by gabrielhpugliese** [comment]
Cool :+1: Gonna try it.

**Comment by jbbr** [comment]
That doesn't mean that you have to delete your PR.
I'm not the owner of this project so I can't decide anything :)

I would prefer a update of this PR using a better source map setting and maybe removal of the redbox-react plugin.
But jedwards1211 has to decided if he also prefers good source maps over this red error.

May be it's even possible to get both - For me the best solution was to just omit this redbox instead of trying to figure out how to fix this.

**Comment by gabrielhpugliese** [comment]
I closed because I didn't know that it did not cache the sourcemap and your PR is way more complete work :)

**Comment by gabrielhpugliese** [comment]
BTW, the redbox-react plugin is not showing the correct line for me even with eval.

**Comment by jbbr** [comment]
Yes but at least it shows the correct file.
If I switch to any of the other source map methods I only get 'client.bundle' references or nothing at all.
Without redbox plugin filename and line numbers are correct in the dev console.

**Comment by gabrielhpugliese** [comment]
Seems reasonable to remove it then.

**Pull request closed without merging**
