### PR TITLE
fix undefined loginButtons

### PR DESCRIPTION
**Pull request by okmttdhr**
@jedwards1211 

I got the error when I run [Running (dev mode)](https://github.com/jedwards1211/meteor-webpack-react#running-dev-mode) in Readme.

`http://localhost:3000/`

Why you need to write `if (!Meteor.isServer)`?

### CODE REVIEW

**Comment by grigio** [comment]
@okmttdhr I think the comment is still valid, because the Login system with Blaze is client-side only.
The current master is broken, is better to switch to a more stable release of this great project https://github.com/jedwards1211/meteor-webpack-react/issues/112

**Comment by okmttdhr** [comment]
Thank you for the information!

**Comment by okmttdhr** [comment]
I've decided to make another project https://github.com/okmttdhr/meteor-react-redux-boilerplate

**Comment by jedwards1211** [comment]
@okmttdhr Fair enough.  You might be interested in my [meteor-immutable-observer](https://github.com/mindfront/meteor-immutable-observer) for putting Meteor collections into the Redux store.

**Comment by vonwao** [comment]
I'm getting this same issue.  I don't understand what's going, why does this fail?  Where is Template.loginButtons supposed to come from? accounts-ui?  In another project I'm using "BlazeToReact" thereactivestack:blazetoreact which works.

**Comment by AdamBrodzinski** [comment]
@vonwao it should be coming from `accounts-ui` and `accounts-password`. Unless those got taken  out?

@jedwards1211 perhaps we should pull the accounts from the example since they seem to be in flux?

**Pull request closed without merging**
