### PR TITLE
Fix error caused by overwriting Template global.

### PR DESCRIPTION
**Pull request by wdhorton**
Because of hoisting of `var` declarations, the lines I removed from App.jsx were causing an error on the client side because they functioned like this:
```
var Template;
if (Meteor.isServer) {
  Template = {
    loginButtons: 'any'
  };		
}
```
This left Template undefined when Meteor.isServer was false. Just changing the `var` to `let` or `const` wouldn't work, as that would confine it to the scope of the `if` statement.

The logic more properly belongs in the render method, where the choice is made to just not render the loginButtons template server-side, because as the comment said, Template does not support server side.

### CODE REVIEW

**Comment by wdhorton** [comment]
I just committed a better solution to this problem, which is to pass the BlazeTemplate component a templateName prop, rather than the template itself. Since the Template global is now called in componentDidMount in BlazeTemplate, it avoids the server-side issue completely, because componentDidMount is never called on the server side.

**Comment by jedwards1211** [comment]
Okay, I finally revisited this...

The real problem was referring to `Template` on the server side to begin with; as I've never really used Blaze I wasn't aware that `Template` isn't available on the server-side and didn't really think twice about the hacky PR that monkeypatched it for SSR's sake.

I think your solution might be more convenient than guarding all usage of `BlazeTemplate` with `Meteor.isClient`, but I think rather than using `componentDidMount` it should just return an empty `<span/>` from `render()` if `!Meteor.isClient` (or perhaps if `typeof Template === 'undefined' etc.)

**Comment by wdhorton** [comment]
I just checked it out, and realized that I didn't add the componentDidMount stuff, it came from the previous implementation of BlazeTemplate. I think it was done that way for a reason: when I tried moving the logic to render, I got this error:

```
Warning: BlazeTemplate is accessing getDOMNode or findDOMNode inside its render(). render() should be a pure function of props and state. It should never access something that requires stale data from the previous render, such as refs. Move this logic to componentDidMount and componentDidUpdate instead.
```

So probably best to leave it as is? I just merged in the new changes from your master branch.

**Comment by jedwards1211** [comment]
Oh right, I hadn't looked at `BlazeTemplate` in a long time.  Since headless React testing and similar things are sometimes done on the server, there are cases in which `componentDidMount` could be called on the server.  So we should just make your `componentDidMount` check if `Template` exists before trying to get the named template.

**Comment by wdhorton** [comment]
I hadn't thought about componentDidMount being called on the server—just added a conditional check for Template in componentDidMount.

**Comment by jedwards1211** [comment]
I fixed the issues with Template awhile ago, and forgot to close these PRs.  Check out the latest master if you haven't already :)

**Pull request closed without merging**
