### PR TITLE
Made the dev, prod, and build scripts generate all required symlinks …

### PR DESCRIPTION
**Pull request by jrmclaurin**
…in meteor_core, instead of juggling dev and prod directories.

### CODE REVIEW

**Comment by jedwards1211** [comment]
Looks good, though I haven't tested it yet.  Should we put a gitignore for the symlink to loadClientBundle.html?

**Comment by jedwards1211** [comment]
Ah, it seems I don't have `pushd` and `popd` on my system.  Is this a common unix practice, to get an absolute path for the symlinks?  I would have just used relative paths for the symlinks, but maybe you know some kind of pitfall I don't.

**Comment by jrmclaurin** [comment]
That was my bad--I believe pushd and popd are part of the bash shell, and not system commands. I switched all of the scripts from #!/bin/sh to #!/bin/bash, which should fix the problem. It seems like some systems alias /bin/sh to /bin/bash, and some don't.

**Comment by jedwards1211** [comment]
Oh right.  Okay, I'll merge and double check this...

**Comment by jedwards1211** [comment]
I guess this doesn't automatically close after manual merge?

**Pull request closed without merging**
