### PR TITLE
updated react to 0.14.0 - added react-dom

### PR DESCRIPTION
**Pull request by ramsaylanier**
react 0.14.0 just came out which extracts DOM stuff into a separate packaing. This PR updates the package.json file and includes ReactDOM where necessary.

### CODE REVIEW

**Comment by rclai** [comment]
Does React Transform still work on the new version?

**Comment by ramsaylanier** [comment]
To my knowledge it does. I'm pretty sure dev.js uses react-transform and I don't get any errors when using React 0.14 currently.

**Comment by jbbr** [comment]
I can confirm that this should work.
I'm using react 0.14 for a while now (since RC 1) and haven't had any issues with hot reload.

**Comment by rclai** [comment]
Cool.

**Comment by jedwards1211** [comment]
Yeah, I've been using React 0.14 without problems.  Thanks!

**Pull request merged**
